name: cozy_clean
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # 状态管理
  flutter_riverpod: ^2.4.9
  
  # 本地数据库
  drift: ^2.14.0
  sqlite3_flutter_libs: ^0.5.18
  path_provider: ^2.1.1
  path: ^1.8.3
  
  # 网络请求
  dio: ^5.4.0
  
  # 存储与安全
  shared_preferences: ^2.2.2
  flutter_secure_storage: ^9.0.0
  
  # 媒体
  photo_manager: ^3.0.0

  # UI 核心
  cupertino_icons: ^1.0.2
  appinio_swiper: ^2.0.0
  confetti: ^0.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  # 代码生成
  build_runner: ^2.4.7
  drift_dev: ^2.14.0
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
